-- LegionCom
-- Authors: ChrispyNut, BackBash
-- https://github.com/nuttyb-community/nuttyb

{
    legcom = {
				footprintx = 2,
        footprintz = 2,
        energymake = 50,
        metalmake = 5,
        health = 6000,
        autoheal = 40,
        buildoptions = {
            'legrezbot',
            'legdtl',
            'legdtf',
            'legdtr',
            'legjam',
            'legwin',
            'leglab',
            'legeconv',
        },
        customparams = {
            evolution_target = 'legcomlvl2',
            evolution_condition = 'timer_global',
            evolution_timer = 420,
            inheritxpratemultiplier = 0.5,
            childreninheritxp = 'TURRET MOBILEBUILT',
            parentsinheritxp = 'TURRET MOBILEBUILT',
        },
        weapondefs = {
            legcomlaser = {
                corethickness = 0.25,
                duration = 0.09,
                name = 'Light close-quarters g2g/g2a laser',
                range = 360,
                reloadtime = 0.20,
                rgbcolor = '0 2 1',
                soundhitdry = '',
                soundhitwet = 'sizzle',
                soundstart = 'lasrcrw1',
                soundtrigger = true,
                sprayangle = 700,
                thickness = 6,
                texture1 = 'shot',
                texture2 = 'empty',
                weapontype = 'LaserCannon',
                weaponvelocity = 2100,
                damage = {
                    default = 250,
                },
            },
            shotgun = {
                areaofeffect = 60,
                energypershot = 0,
                avoidfeature = false,
                craterboost = 0,
                cratermult = 0,
                cameraShake = 0,
                edgeeffectiveness = 0.65,
                explosiongenerator = 'custom:genericshellexplosion-small',
                impulseboost = 0.2,
                impulsefactor = 0.2,
                intensity = 3,
                name = '6 Gauge Shotgun',
                noselfdamage = true,
                predictboost = 1,
                projectiles = 6,
                range = 320,
                reloadtime = 2,
                rgbcolor = '1 0.75 0.25',
                size = 2,
                soundhit = 'xplomed2xs',
                soundhitwet = 'splsmed',
                soundstart = 'kroggie2xs',
                soundstartvolume = 12,
                sprayangle = 2000,
                turret = true,
                commandfire = true,
                weapontimer = 1,
                weapontype = 'Cannon',
                weaponvelocity = 600,
                stockpile = true,
                stockpiletime = 5,
                customparams = {
                    stockpilelimit = 10,
                },
                damage = {
                    default = 1800,
                    commanders = 0,
                },
            },
        },
        weapons = {
            [3] = {
                def = 'shotgun',
                onlytargetcategory = 'SURFACE',
            },
        },
    },
    legcomlvl2 = {
				footprintx = 2,
        footprintz = 2,
        energymake = 150,
        metalmake = 15,
        speed = 57.5,
        autoheal = 100,
        health = 6700,
        customparams = {
            evolution_condition = 'timer_global',
            evolution_timer = 1020,
            inheritxpratemultiplier = 0.5,
            childreninheritxp = 'TURRET MOBILEBUILT',
            parentsinheritxp = 'TURRET MOBILEBUILT',
        },
        buildoptions = {
            'legrezbot',
            'legadvsol',
            'corhllt',
            'leggeo',
            'legnanotc',
            'legjam',
            'legdtf',
            'legmg',
            'legrad',
            'legdtl',
            'legdtr',
            'legrhapsis',
            'legwin',
            'legeconv',
        },
        weapondefs = {
            legcomlaser = {
                accuracy = 50,
                areaofeffect = 12,
                avoidfriendly = false,
                avoidfeature = false,
                collidefriendly = false,
                collidefeature = true,
                beamtime = 0.09,
                corethickness = 0.3,
                duration = 0.09,
                explosiongenerator = 'custom:laserhit-small-red',
                firestarter = 70,
                impactonly = 1,
                impulseboost = 0,
                impulsefactor = 0,
                name = 'Light close-quarters g2g/g2a laser',
                noselfdamage = true,
                range = 500,
                reloadtime = 0.2,
                rgbcolor = '0 0.95 0.05',
                soundhitdry = '',
                soundhitwet = 'sizzle',
                soundstart = 'lasrcrw1',
                soundtrigger = true,
                sprayangle = 500,
                targetmoveerror = 0.05,
                thickness = 7,
                tolerance = 1000,
                texture1 = 'shot',
                texture2 = 'empty',
                turret = true,
                weapontype = 'LaserCannon',
                weaponvelocity = 2200,
                damage = {
                    bombers = 180,
                    default = 450,
                    fighters = 110,
                    subs = 5,
                },
            },
            shotgun = {
                areaofeffect = 65,
                energypershot = 0,
                avoidfeature = false,
                craterboost = 0,
                cratermult = 0,
                cameraShake = 0,
                edgeeffectiveness = 0.65,
                explosiongenerator = 'custom:genericshellexplosion-small',
                impulseboost = 0.2,
                impulsefactor = 0.2,
                intensity = 3,
                name = '12 Gauge Shotgun',
                noselfdamage = true,
                predictboost = 1,
                projectiles = 7,
                range = 440,
                reloadtime = 2,
                rgbcolor = '1 0.75 0.25',
                size = 2.5,
                soundhit = 'xplomed2xs',
                soundhitwet = 'splsmed',
                soundstart = 'kroggie2xs',
                soundstartvolume = 12,
                sprayangle = 2250,
                turret = true,
                commandfire = true,
                weapontimer = 1,
                weapontype = 'Cannon',
                weaponvelocity = 600,
                stockpile = true,
                stockpiletime = 5,
                customparams = {
                    stockpilelimit = 15,
                },
                damage = {
                    default = 2200,
                    commanders = 0,
                },
            },
        },
        weapons = {
            [1] = {
                def = 'legcomlaser',
                onlytargetcategory = 'NOTSUB',
                fastautoretargeting = true,
            },
            [3] = {
                def = 'shotgun',
                onlytargetcategory = 'SURFACE',
            },
        },
    },
    legcomlvl3 = {
				footprintx = 2,
        footprintz = 2,
        energymake = 1280,
        metalmake = 40,
        speed = 70.5,
        workertime = 700,
        autoheal = 150,
        health = 7500,
        customparams = {
            evolution_condition = 'timer_global',
            evolution_timer = 1440,
            inheritxpratemultiplier = 0.5,
            childreninheritxp = 'TURRET MOBILEBUILT',
            parentsinheritxp = 'TURRET MOBILEBUILT',
        },
        buildoptions = {
            'legdeflector',
            'legfus',
            'legbombard',
            'legadvestore',
            'legmoho',
            'legadveconv',
            'legarad',
            'legajam',
            'legforti',
            'legacluster',
            'legamstor',
            'legflak',
            'legabm',
            'legbastion',
            'legdtr',
            'legdtf',
            'legrezbot',
            'legdtl',
            'leglab',
            'legbastiont4',
            'legnanotct3',
            'legapopupdef',
            'epic_starfall',
            'epic_bastion',
            'epic_sentinel',
        },
        weapondefs = {
            legcomlaser = {
                accuracy = 50,
                areaofeffect = 12,
                avoidfriendly = true,
                avoidfeature = true,
                collidefriendly = false,
                collidefeature = true,
                beamtime = 0.09,
                corethickness = 0.55,
                duration = 0.09,
                explosiongenerator = 'custom:laserhit-small-red',
                firestarter = 70,
                impactonly = 0,
                impulseboost = 0,
                impulsefactor = 0,
                name = 'Light close-quarters g2g/g2a laser',
                noselfdamage = true,
                range = 640,
                reloadtime = 0.2,
                rgbcolor = '0 0.2 0.8',
                soundhitdry = '',
                soundhitwet = 'sizzle',
                soundstart = 'lasrcrw1',
                soundtrigger = true,
                sprayangle = 500,
                targetmoveerror = 0.05,
                thickness = 7,
                tolerance = 1000,
                texture1 = 'shot',
                texture2 = 'empty',
                turret = true,
                weapontype = 'LaserCannon',
                weaponvelocity = 2500,
                damage = {
                    bombers = 180,
                    default = 650,
                    fighters = 110,
                    subs = 5,
                },
            },
            shotgun = {
                areaofeffect = 90,
                energypershot = 0,
                avoidfeature = false,
                craterboost = 0,
                cratermult = 0,
                cameraShake = 0,
                edgeeffectiveness = 0.65,
                explosiongenerator = 'custom:genericshellexplosion-small',
                impulseboost = 0.2,
                impulsefactor = 0.2,
                intensity = 3,
                name = '12 Gauge Shotgun',
                noselfdamage = true,
                predictboost = 1,
                projectiles = 7,
                range = 540,
                reloadtime = 2,
                rgbcolor = '1 0.75 0.25',
                size = 2.5,
                soundhit = 'xplomed2xs',
                soundhitwet = 'splsmed',
                soundstart = 'kroggie2xs',
                soundstartvolume = 12,
                sprayangle = 2500,
                turret = true,
                commandfire = true,
                weapontimer = 1,
                weapontype = 'Cannon',
                weaponvelocity = 600,
                stockpile = true,
                stockpiletime = 5,
                customparams = {
                    stockpilelimit = 20,
                },
                damage = {
                    default = 3200,
                    commanders = 0,
                },
            },
        },
        weapons = {
            [1] = {
                def = 'legcomlaser',
                onlytargetcategory = 'NOTSUB',
                fastautoretargeting = true,
            },
            [3] = {
                def = 'shotgun',
                onlytargetcategory = 'SURFACE',
            },
            [5] = {
                def = '',
            },
        },
    },
    legcomlvl4 = {
				footprintx = 2,
        footprintz = 2,
        energymake = 1980,
        metalmake = 46,
        speed = 88.5,
        workertime = 1000,
        autoheal = 180,
        health = 24500,
        customparams = {
            evolution_condition = 'timer_global',
            evolution_timer = 1740,
            inheritxpratemultiplier = 0.5,
            childreninheritxp = 'TURRET MOBILEBUILT',
            parentsinheritxp = 'TURRET MOBILEBUILT',
        },
        buildoptions = {
            'legdeflector',
            'legfus',
            'legbombard',
            'legadvestore',
            'legmoho',
            'legadveconv',
            'legeshotgunmech',
            'legarad',
            'legajam',
            'legkeres',
            'legacluster',
            'legamstor',
            'legflak',
            'legabm',
            'legbastion',
            'legbastiont4',
            'legnanotct2',
            'legnanotct2plat',
            'legrwall',
            'leglab',
            'legtarg',
            'legsd',
            'legpede',
            'legerailtank',
            'legeheatraymech',
            'legrezbot',
            'legafus',
            'leglraa',
            'legdtl',
            'legdtf',
            'legministarfall',
            'legstarfall',
            'leggatet3',
            'legperdition',
            'legsilo',
            'legsrailt4',
            'legelrpcmech',
            'legdtr',
            'legnanotct3',
            'legapopupdef',
            'leglrpc',
            'epic_starfall',
            'epic_bastion',
            'epic_sentinel',
        },
        weapondefs = {
            legcomlaser = {
                accuracy = 50,
                areaofeffect = 12,
                avoidfriendly = true,
                avoidfeature = true,
                collidefriendly = false,
                collidefeature = true,
                beamtime = 0.1,
                corethickness = 0.5,
                duration = 0.09,
                explosiongenerator = 'custom:laserhit-small-red',
                firestarter = 70,
                impactonly = 0,
                impulseboost = 0,
                impulsefactor = 0,
                name = 'Light close-quarters g2g/g2a laser',
                noselfdamage = true,
                range = 900,
                reloadtime = 0.1,
                rgbcolor = '0.45 0 1',
                soundhitdry = '',
                soundhitwet = 'sizzle',
                soundstart = 'lasrcrw1',
                soundtrigger = 1,
                sprayangle = 400,
                targetmoveerror = 0.05,
                thickness = 6,
                tolerance = 1000,
                texture1 = 'shot',
                texture2 = 'empty',
                turret = true,
                weapontype = 'LaserCannon',
                weaponvelocity = 3000,
                damage = {
                    bombers = 180,
                    default = 1750,
                    fighters = 110,
                    subs = 5,
                },
            },
            shotgun = {
                areaofeffect = 75,
                energypershot = 0,
                avoidfeature = false,
                craterboost = 0,
                cratermult = 0,
                cameraShake = 0,
                edgeeffectiveness = 0.65,
                explosiongenerator = 'custom:genericshellexplosion-small',
                impulseboost = 0.2,
                impulsefactor = 0.2,
                intensity = 3,
                name = '60 Gauge Raptor Popper',
                noselfdamage = true,
                predictboost = 1,
                projectiles = 9,
                range = 550,
                reloadtime = 1,
                rgbcolor = '1 0.75 0.25',
                size = 5,
                soundhit = 'xplomed2xs',
                soundhitwet = 'splsmed',
                soundstart = 'kroggie2xs',
                soundstartvolume = 12,
                sprayangle = 3000,
                turret = true,
                commandfire = true,
                weapontimer = 1,
                weapontype = 'Cannon',
                weaponvelocity = 600,
                stockpile = true,
                stockpiletime = 4,
                customparams = {
                    stockpilelimit = 20,
                },
                damage = {
                    default = 4400,
                    commanders = 0,
                },
            },
        },
        weapons = {
            [1] = {
                def = 'legcomlaser',
                onlytargetcategory = 'NOTSUB',
                fastautoretargeting = true,
            },
            [3] = {
                def = 'shotgun',
                onlytargetcategory = 'SURFACE',
            },
            [5] = {
                def = '',
            },
        },
    },
    legcomlvl5 = {
				footprintx = 2,
        footprintz = 2,
        energymake = 2280,
        metalmake = 64,
        speed = 100,
        workertime = 1700,
        autoheal = 4500,
        health = 53900,
        customparams = {
            inheritxpratemultiplier = 0.5,
            childreninheritxp = 'TURRET MOBILEBUILT',
            parentsinheritxp = 'TURRET MOBILEBUILT',
        },
        buildoptions = {
            'legdeflector',
            'legfus',
            'legbombard',
            'legadvestore',
            'legmoho',
            'legadveconv',
            'legeshotgunmech',
            'legarad',
            'legajam',
            'legkeres',
            'legacluster',
            'legamstor',
            'legflak',
            'legabm',
            'legbastion',
            'legbastiont4',
            'legnanotct2',
            'legnanotct2plat',
            'legrwall',
            'leglab',
            'legtarg',
            'legsd',
            'legpede',
            'legerailtank',
            'legeheatraymech',
            'legrezbot',
            'legafus',
            'leglraa',
            'legdtl',
            'legdtf',
            'legministarfall',
            'legstarfall',
            'leggatet3',
            'legperdition',
            'legsilo',
            'legsrailt4',
            'legelrpcmech',
            'legdtr',
            'legnanotct3',
            'legapopupdef',
            'leglrpc',
            'epic_starfall',
            'epic_bastion',
            'epic_sentinel',
        },
        weapondefs = {
            machinegun = {
                accuracy = 80,
                areaofeffect = 10,
                avoidfeature = false,
                beamburst = true,
                beamdecay = 1,
                beamtime = 0.07,
                burst = 6,
                burstrate = 0.10667,
                camerashake = 0,
                corethickness = 0.35,
                craterareaofeffect = 0,
                craterboost = 0,
                cratermult = 0,
                edgeeffectiveness = 1,
                explosiongenerator = 'custom:laserhit-medium-red',
                firestarter = 10,
                impulsefactor = 0,
                largebeamlaser = true,
                laserflaresize = 30,
                name = 'Rapid-fire close quarters g2g armor-piercing laser',
                noselfdamage = true,
                pulsespeed = q8,
                range = 1100,
                reloadtime = 0.50,
                rgbcolor = '0.7 0.3 1.0',
                rgbcolor2 = '0.8 0.6 1.0',
                soundhitdry = '',
                soundhitwet = 'sizzle',
                soundstart = 'lasfirerc',
                soundtrigger = 1,
                sprayangle = 500,
                targetborder = 0.2,
                thickness = 5.5,
                tolerance = 4500,
                turret = true,
                weapontype = 'BeamLaser',
                weaponvelocity = 920,
                damage = {
                    default = 1300,
                    vtol = 180,
                },
            },
            shotgunarm = {
                areaofeffect = 112,
                commandfire = true,
                avoidfeature = false,
                craterboost = 0,
                cratermult = 0,
                cameraShake = 0,
                edgeeffectiveness = 0.65,
                explosiongenerator = 'custom:genericshellexplosion-medium',
                impulsefactor = 0.8,
                intensity = 0.2,
                mygravity = 1,
                name = 'GaussCannon',
                noselfdamage = true,
                predictboost = 1,
                projectiles = 20,
                range = 650,
                reloadtime = 1,
                rgbcolor = '0.8 0.4 1.0',
                size = 4,
                sizeDecay = 0.044,
                stages = 16,
                alphaDecay = 0.66,
                soundhit = 'xplomed2xs',
                soundhitwet = 'splsmed',
                soundstart = 'kroggie2xs',
                sprayangle = 3500,
                tolerance = 6000,
                turret = true,
                waterweapon = true,
                weapontimer = 2,
                weapontype = 'Cannon',
                weaponvelocity = 900,
                stockpile = true,
                stockpiletime = 2,
                customparams = {
                    stockpilelimit = 50,
                },
                damage = {
                    default = 10000,
                    commanders = 0,
                },
            },
            exp_heavyrocket = {
                areaofeffect = 70,
                collidefriendly = 0,
                collidefeature = 0,
                cameraShake = 0,
                energypershot = 125,
                avoidfeature = 0,
                avoidfriendly = 0,
                burst = 4,
                burstrate = 0.3,
                cegtag = 'missiletrailsmall-red',
                colormap = '0.75 0.73 0.67 0.024   0.37 0.4 0.30 0.021   0.22 0.21 0.14 0.018  0.024 0.014 0.009 0.03   0.0 0.0 0.0 0.008',
                craterboost = 0,
                craterareaofeffect = 0,
                cratermult = 0,
                dance = 24,
                edgeeffectiveness = 0.65,
                explosiongenerator = 'custom:burnblack',
                firestarter = 70,
                flighttime = 1.05,
                flamegfxtime = 1,
                impulsefactor = 0.123,
                impactonly = 1,
                model = 'catapultmissile.s3o',
                movingaccuracy = 600,
                name = 'Raptor Boomer',
                noselfdamage = true,
                proximitypriority = nil,
                range = 700,
                reloadtime = 1,
                smoketrail = true,
                smokePeriod = 4,
                smoketime = 16,
                smokesize = 8.5,
                smokecolor = 0.5,
                size = 2,
                smokeTrailCastShadow = false,
                soundhit = 'rockhit',
                soundhitwet = 'splsmed',
                soundstart = 'rapidrocket3',
                startvelocity = 165,
                rgbcolor = '1 0.25 0.1',
                texture1 = 'null',
                texture2 = 'smoketrailbar',
                trajectoryheight = 1,
                targetmoveerror = 0.2,
                turnrate = 5000,
                tracks = true,
                turret = true,
                allowNonBlockingAim = true,
                weaponacceleration = 660,
                weapontimer = 6,
                weapontype = 'MissileLauncher',
                weaponvelocity = 950,
                wobble = 2000,
                damage = {
                    default = 1300,
                },
                customparams = {
                    exclude_preaim = true,
                    overrange_distance = 777,
                    projectile_destruction_method = 'descend',
                },
            },
        },
        weapons = {
            [1] = {
                def = 'machinegun',
                onlytargetcategory = 'NOTSUB',
                fastautoretargeting = true,
            },
            [3] = {
                def = 'shotgunarm',
                onlytargetcategory = 'WEAPON',
            },
            [5] = {
                def = 'exp_heavyrocket',
                onlytargetcategory = 'SURFACE',
            },
        },
    },
}
