-- T4RFLRPC
-- Balance on T4 RFLRPC
-- Authors: Altwaal
-- https://github.com/nuttyb-community/nuttyb

{
    armvulc = {
        explodeas = 'fusionExplosion',
        energycost = 1500000,
        metalcost = 55000,
        buildtime = 180000,
        health = 52000,
        footprintx = 6,
        footprintz = 6,
        weapondefs = {
            ARMVULC_MAIN = {
                areaofeffect = 120,
                collidefriendly = 0,
                collidefeature = 0,
                avoidfeature = 0,
                avoidfriendly = 0,
                beamtime = 0.5,
                burst = 1,
                corethickness = 0.1,
                craterareaofeffect = 90,
                craterboost = 0,
                cratermult = 0,
                cameraShake = 0,
                edgeeffectiveness = 0.30,
                energypershot = 3200,
                explosiongenerator = 'custom:laserhit-large-red',
                firestarter = 90,
                impactonly = 1,
                impulseboost = 0,
                impulsefactor = 0,
                largebeamlaser = true,
                laserflaresize = 1,
                name = 'The Eagle Standard',
                noselfdamage = true,
                range = 2900,
                reloadtime = 0.3,
                rgbcolor = '0/1/0.4',
                scrollspeed = 13,
                soundhitdry = '',
                soundhitwet = 'sizzle',
                soundstart = 'lasrcrw1',
                soundtrigger = 1,
                targetmoveerror = 0.3,
                texture3 = 'largebeam',
                thickness = 12,
                tilelength = 150,
                tolerance = 10000,
                turret = true,
                turnrate = 16000,
                weapontype = 'LaserCannon',
                weaponvelocity = 3100,
                damage = {
                    commanders = 480,
                    default = 2550,
                },
            },
        },
        weapons = {
            [1] = {
                badtargetcategory = 'VTOL GROUNDSCOUT',
                def = 'ARMVULC_MAIN',
                onlytargetcategory = 'SURFACE',
            },
        },
    },

    corbuzz = {
        explodeas = 'fusionExplosion',
        energycost = 1500000,
        metalcost = 58000,
        buildtime = 190000,
        health = 54000,
        footprintx = 6,
        footprintz = 6,
        weapondefs = {
            CORBUZZ_MAIN = {
                areaofeffect = 220,
                collidefriendly = 0,
                collidefeature = 0,
                avoidfeature = 0,
                avoidfriendly = 0,
                burst = 1,
                craterareaofeffect = 140,
                craterboost = 0,
                cratermult = 0,
                cameraShake = 0,
                edgeeffectiveness = 0.45,
                energypershot = 2500,
                explosiongenerator = 'custom:plasmahit-large-blue',
                firestarter = 85,
                impactonly = 1,
                impulseboost = 0,
                impulsefactor = 0.8,
                name = 'Cortex Devastator',
                noselfdamage = true,
                range = 2800,
                reloadtime = 0.167,
                rgbcolor = '0.2/0.8/1.0',
                soundhitdry = 'xplomed2',
                soundhitwet = 'splshbig',
                soundstart = 'cannhvy5',
                soundtrigger = 1,
                targetmoveerror = 0.25,
                thickness = 8,
                tolerance = 8000,
                turret = true,
                turnrate = 14000,
                weapontype = 'Cannon',
                weaponvelocity = 2800,
                damage = {
                    commanders = 480,
                    default = 1333,
                },
            },
        },
        weapons = {
            [1] = {
                badtargetcategory = 'VTOL GROUNDSCOUT',
                def = 'CORBUZZ_MAIN',
                onlytargetcategory = 'SURFACE',
            },
        },
    },

    legstarfall = {
        explodeas = 'fusionExplosion',
        energycost = 1500000,
        metalcost = 52000,
        buildtime = 175000,
        health = 48000,
        footprintx = 6,
        footprintz = 6,
        weapondefs = {
            LEGSTARFALL_MAIN = {
                accuracy = 0,
                areaofeffect = 220,
                avoidfeature = false,
                avoidfriendly = false,
                avoidground = false,
                burst = 20,
                burstrate = 0.015,
                sprayangle = 120,
                highTrajectory = 0,
                cegtag = 'starfire',
                collidefriendly = false,
                craterboost = 0.1,
                impactonly = 1,
                cratermult = 0.1,
                edgeeffectiveness = 0.75,
                energypershot = 4480,
                fireTolerance = 200,
                tolerance = 200,
                explosiongenerator = 'custom:plasmahit-medium-purple',
                gravityaffected = false,
                impulsefactor = 0.4,
                name = 'Legion Meteor Storm',
                noselfdamage = true,
                range = 2950,
                reloadtime = 1.5,
                cameraShake = 0,
                rgbcolor = '0.7 0.3 1.0',
                soundhit = 'xplomed4',
                soundhitwet = 'splshbig',
                soundstart = 'mortarhvy1',
                soundhitvolume = 35,
                turret = true,
                weapontimer = 3,
                weapontype = 'Cannon',
                weaponvelocity = 1200,
                damage = {
                    commanders = 480,
                    default = 650,
                    shields = 200,
                    sub = 60,
                },
            },
        },
        weapons = {
            [1] = {
                badtargetcategory = 'VTOL GROUNDSCOUT',
                def = 'LEGSTARFALL_MAIN',
                onlytargetcategory = 'SURFACE',
                burstControlWhenOutOfArc = 1,
                maindir = '0 0 1',
            },
        },
    },
}
